const autocompleteProducts = [
    "tv",
    "fridge",
    "laptop",
    "smartphone",
    "headphones",
    "tablet",
    "camera",
    "microwave",
    "washing machine",
    "vacuum cleaner",
    "coffee maker",
    "blender",
    "toaster",
    "iron",
    "hair dryer",
    "air conditioner",
    "fan",
    "printer",
    "monitor",
    "keyboard",
    "mouse",
    "speakers",
    "gaming console",
    "external hard drive",
    "router",
    "fitness tracker",
    "smartwatch",
    "backpack",
    "shoes",
    "dress",
    "jeans",
    "shirt",
    "t-shirt",
    "sweater",
    "jacket",
    "watch",
    "sunglasses",
    "perfume",
    "wallet",
    "handbag",
    "chocolates",
    "coffee",
    "tea",
    "wine",
    "water bottle",
    "luggage",
    "camping tent",
    "sleeping bag",
    "hiking boots",
    "guitar",
    "keyboard (musical instrument)",
    "drums",
    "microphone",
    "book",
    "ebook reader",
    "board game",
    "puzzle",
    "art supplies",
    "yoga mat",
    "dumbbells",
    "treadmill",
    "bicycle",
    "skateboard",
    "scooter",
    "pet food",
    "pet toys",
    "plant",
    "gardening tools",
    "cookware set",
    "dinnerware set",
    "cutlery set",
    "bakeware set",
    "bedding set",
    "towel set",
    "curtains",
    "rug",
    "pillow",
    "wall art",
    "desk",
    "office chair",
    "back support cushion",
    "whiteboard",
    "stationery",
    "garden hose",
    "grill",
    "paint",
    "umbrella",
    "sunscreen",
    "backpack",
    "fishing rod",
    "kayak",
    "hiking shoes",
    "bathrobe",
    "slippers",
    "smart thermostat",
    "security camera",
    "doorbell",
    "smart bulb",
    "robot vacuum",
    "robot lawn mower",
    "wireless earbuds",
    "portable charger",
    "projector",
    "air purifier",
    "baby stroller",
    "car seat",
    "diaper bag",
    "baby monitor",
    "baby bottle",
    "baby pacifier",
    "baby blanket",
    "baby onesie",
    "baby shoes",
    "baby toys",
    "diapers",
    "nail polish",
    "lipstick",
    "foundation",
    "eyeshadow",
    "mascara",
    "shampoo",
    "conditioner",
    "body wash",
    "toothbrush",
    "toothpaste",
    "razor",
    "shaving cream",
    "deodorant",
];

export default autocompleteProducts;